In [9]:
# Notebook da tekshiring
import pandas as pd
import os

path = r"C:\Users\hamid\Desktop\git_project\Data\Raw_Data\all_stocks.csv"
df = pd.read_csv(path)

print(df["Ticker"].unique())   # ← barcha kompaniyalar
print(df.shape)                # ← qatorlar soni

['AAPL' 'TSLA' 'MSFT' 'GOOGL' 'AMZN' 'META' 'NVDA' 'NFLX' 'INTC' 'AMD'
 'TSM' 'BABA']
(3012, 10)

In [10]:
import sys
import os

notebook_dir = os.path.abspath("")
BASE_DIR = os.path.dirname(notebook_dir)
sys.path.append(os.path.join(BASE_DIR, "scripts"))

from data_load import load_data

# ✅ Ishlayaptimi tekshiring
df = load_data()
print(df.head(10))

                        Date        Open        High         Low       Close  \
0  2025-06-06 00:00:00-04:00  202.197834  204.887162  201.251591  203.114197
1  2025-06-09 00:00:00-04:00  203.582346  205.185985  199.229619  200.653961
2  2025-06-10 00:00:00-04:00  199.807343  203.542525  199.777463  201.869156
3  2025-06-11 00:00:00-04:00  202.695872  203.691921  197.625989  197.994522
4  2025-06-12 00:00:00-04:00  198.293336  198.890956  196.580131  198.412857
5  2025-06-13 00:00:00-04:00  198.940744  199.578214  194.926670  195.673706
6  2025-06-16 00:00:00-04:00  196.520356  197.904863  195.783275  197.635925
7  2025-06-17 00:00:00-04:00  196.420746  197.606046  194.438619  194.866913
8  2025-06-18 00:00:00-04:00  195.165737  196.789301  194.299180  195.803207
9  2025-06-20 00:00:00-04:00  197.456661  200.902980  196.082109  200.205750

     Volume  Dividends  Stock Splits Ticker Currency
0  46607700        0.0           0.0   AAPL      USD
1  72862600        0.0           0.0   AAPL      USD
2  54672600        0.0           0.0   AAPL      USD
3  60989900        0.0           0.0   AAPL      USD
4  43904600        0.0           0.0   AAPL      USD
5  51447300        0.0           0.0   AAPL      USD
6  43020700        0.0           0.0   AAPL      USD
7  38856200        0.0           0.0   AAPL      USD
8  45394700        0.0           0.0   AAPL      USD
9  96813500        0.0           0.0   AAPL      USD

In [11]:
# 2️⃣ CELL - datani yuklash
df = load_data()

In [12]:
# 3️⃣ CELL - tekshirish
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Currency
0,2025-06-06 00:00:00-04:00,202.197834,204.887162,201.251591,203.114197,46607700,0.0,0.0,AAPL,USD
1,2025-06-09 00:00:00-04:00,203.582346,205.185985,199.229619,200.653961,72862600,0.0,0.0,AAPL,USD
2,2025-06-10 00:00:00-04:00,199.807343,203.542525,199.777463,201.869156,54672600,0.0,0.0,AAPL,USD
3,2025-06-11 00:00:00-04:00,202.695872,203.691921,197.625989,197.994522,60989900,0.0,0.0,AAPL,USD
4,2025-06-12 00:00:00-04:00,198.293336,198.890956,196.580131,198.412857,43904600,0.0,0.0,AAPL,USD

In [13]:
# 4️⃣ CELL - ma'lumot haqida
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3012 entries, 0 to 3011
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3012 non-null   object
 1   Open          3012 non-null   float64
 2   High          3012 non-null   float64
 3   Low           3012 non-null   float64
 4   Close         3012 non-null   float64
 5   Volume        3012 non-null   int64
 6   Dividends     3012 non-null   float64
 7   Stock Splits  3012 non-null   float64
 8   Ticker        3012 non-null   object
 9   Currency      3012 non-null   object
dtypes: float64(6), int64(1), object(3)
memory usage: 235.4+ KB

In [14]:
# 5️⃣ CELL - statistika
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,3012.000000,3012.000000,3012.000000,3012.000000,3.012000e+03,3012.000000,3012.00000
mean,275.457624,279.034062,271.686249,275.440983,5.423722e+07,0.004393,0.00332
std,170.807281,172.570176,168.673761,170.603516,5.289156e+07,0.062143,0.18221
min,19.500000,19.549999,18.969999,19.309999,2.753900e+06,0.000000,0.00000
25%,160.102497,162.367500,157.659996,160.327503,1.911748e+07,0.000000,0.00000
50%,232.925003,235.495767,230.159377,232.782745,3.730995e+07,0.000000,0.00000
75%,370.267509,374.007622,365.212583,370.525002,6.462768e+07,0.000000,0.00000
max,789.296390,794.384398,778.990557,788.148987,5.239080e+08,2.000000,10.00000

In [15]:
import os
print(os.getcwd())

c:\Users\hamid\Desktop\git_project\Notebooks

In [16]:
os.listdir()

['.ipynb',
 'data_analysis.ipynb',
 'data_loading.ipynb',
 'data_preprocessing.ipynb',
 'feature_creation.ipynb',
 'ReadMe.md']

In [25]:
os.listdir("..")

['.git',
 '.gitattributes',
 '.gitignore',
 '.vscode',
 'Data',
 'errors',
 'log',
 'models',
 'myenv',
 'Notebooks',
 'pipline',
 'ReadMe.md',
 'requirements.txt',
 'results',
 'scripts',
 'src',
 'src__init__.py',
 'test',
 'test_env']

In [26]:
import pandas as pd

# load data
df = pd.read_csv("../Data/Raw_Data/all_stocks.csv")

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3012 entries, 0 to 3011
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3012 non-null   object
 1   Open          3012 non-null   float64
 2   High          3012 non-null   float64
 3   Low           3012 non-null   float64
 4   Close         3012 non-null   float64
 5   Volume        3012 non-null   int64
 6   Dividends     3012 non-null   float64
 7   Stock Splits  3012 non-null   float64
 8   Ticker        3012 non-null   object
 9   Currency      3012 non-null   object
dtypes: float64(6), int64(1), object(3)
memory usage: 235.4+ KB

In [21]:
df['Close'].value_counts()

Close
222.690002    3
44.060001     3
232.380005    2
329.649994    2
237.208923    2
             ..
229.002136    1
232.671753    1
232.123306    1
230.936661    1
203.114197    1
Name: count, Length: 2961, dtype: int64

In [22]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

Date ['2025-06-06 00:00:00-04:00' '2025-06-09 00:00:00-04:00'
 '2025-06-10 00:00:00-04:00' '2025-06-11 00:00:00-04:00'
 '2025-06-12 00:00:00-04:00' '2025-06-13 00:00:00-04:00'
 '2025-06-16 00:00:00-04:00' '2025-06-17 00:00:00-04:00'
 '2025-06-18 00:00:00-04:00' '2025-06-20 00:00:00-04:00'
 '2025-06-23 00:00:00-04:00' '2025-06-24 00:00:00-04:00'
 '2025-06-25 00:00:00-04:00' '2025-06-26 00:00:00-04:00'
 '2025-06-27 00:00:00-04:00' '2025-06-30 00:00:00-04:00'
 '2025-07-01 00:00:00-04:00' '2025-07-02 00:00:00-04:00'
 '2025-07-03 00:00:00-04:00' '2025-07-07 00:00:00-04:00'
 '2025-07-08 00:00:00-04:00' '2025-07-09 00:00:00-04:00'
 '2025-07-10 00:00:00-04:00' '2025-07-11 00:00:00-04:00'
 '2025-07-14 00:00:00-04:00' '2025-07-15 00:00:00-04:00'
 '2025-07-16 00:00:00-04:00' '2025-07-17 00:00:00-04:00'
 '2025-07-18 00:00:00-04:00' '2025-07-21 00:00:00-04:00'
 '2025-07-22 00:00:00-04:00' '2025-07-23 00:00:00-04:00'
 '2025-07-24 00:00:00-04:00' '2025-07-25 00:00:00-04:00'
 '2025-07-28 00:00:00-04:00' '2025-07-29 00:00:00-04:00'
 '2025-07-30 00:00:00-04:00' '2025-07-31 00:00:00-04:00'
 '2025-08-01 00:00:00-04:00' '2025-08-04 00:00:00-04:00'
 '2025-08-05 00:00:00-04:00' '2025-08-06 00:00:00-04:00'
 '2025-08-07 00:00:00-04:00' '2025-08-08 00:00:00-04:00'
 '2025-08-11 00:00:00-04:00' '2025-08-12 00:00:00-04:00'
 '2025-08-13 00:00:00-04:00' '2025-08-14 00:00:00-04:00'
 '2025-08-15 00:00:00-04:00' '2025-08-18 00:00:00-04:00'
 '2025-08-19 00:00:00-04:00' '2025-08-20 00:00:00-04:00'
 '2025-08-21 00:00:00-04:00' '2025-08-22 00:00:00-04:00'
 '2025-08-25 00:00:00-04:00' '2025-08-26 00:00:00-04:00'
 '2025-08-27 00:00:00-04:00' '2025-08-28 00:00:00-04:00'
 '2025-08-29 00:00:00-04:00' '2025-09-02 00:00:00-04:00'
 '2025-09-03 00:00:00-04:00' '2025-09-04 00:00:00-04:00'
 '2025-09-05 00:00:00-04:00' '2025-09-08 00:00:00-04:00'
 '2025-09-09 00:00:00-04:00' '2025-09-10 00:00:00-04:00'
 '2025-09-11 00:00:00-04:00' '2025-09-12 00:00:00-04:00'
 '2025-09-15 00:00:00-04:00' '2025-09-16 00:00:00-04:00'
 '2025-09-17 00:00:00-04:00' '2025-09-18 00:00:00-04:00'
 '2025-09-19 00:00:00-04:00' '2025-09-22 00:00:00-04:00'
 '2025-09-23 00:00:00-04:00' '2025-09-24 00:00:00-04:00'
 '2025-09-25 00:00:00-04:00' '2025-09-26 00:00:00-04:00'
 '2025-09-29 00:00:00-04:00' '2025-09-30 00:00:00-04:00'
 '2025-10-01 00:00:00-04:00' '2025-10-02 00:00:00-04:00'
 '2025-10-03 00:00:00-04:00' '2025-10-06 00:00:00-04:00'
 '2025-10-07 00:00:00-04:00' '2025-10-08 00:00:00-04:00'
 '2025-10-09 00:00:00-04:00' '2025-10-10 00:00:00-04:00'
 '2025-10-13 00:00:00-04:00' '2025-10-14 00:00:00-04:00'
 '2025-10-15 00:00:00-04:00' '2025-10-16 00:00:00-04:00'
 '2025-10-17 00:00:00-04:00' '2025-10-20 00:00:00-04:00'
 '2025-10-21 00:00:00-04:00' '2025-10-22 00:00:00-04:00'
 '2025-10-23 00:00:00-04:00' '2025-10-24 00:00:00-04:00'
 '2025-10-27 00:00:00-04:00' '2025-10-28 00:00:00-04:00'
 '2025-10-29 00:00:00-04:00' '2025-10-30 00:00:00-04:00'
 '2025-10-31 00:00:00-04:00' '2025-11-03 00:00:00-05:00'
 '2025-11-04 00:00:00-05:00' '2025-11-05 00:00:00-05:00'
 '2025-11-06 00:00:00-05:00' '2025-11-07 00:00:00-05:00'
 '2025-11-10 00:00:00-05:00' '2025-11-11 00:00:00-05:00'
 '2025-11-12 00:00:00-05:00' '2025-11-13 00:00:00-05:00'
 '2025-11-14 00:00:00-05:00' '2025-11-17 00:00:00-05:00'
 '2025-11-18 00:00:00-05:00' '2025-11-19 00:00:00-05:00'
 '2025-11-20 00:00:00-05:00' '2025-11-21 00:00:00-05:00'
 '2025-11-24 00:00:00-05:00' '2025-11-25 00:00:00-05:00'
 '2025-11-26 00:00:00-05:00' '2025-11-28 00:00:00-05:00'
 '2025-12-01 00:00:00-05:00' '2025-12-02 00:00:00-05:00'
 '2025-12-03 00:00:00-05:00' '2025-12-04 00:00:00-05:00'
 '2025-12-05 00:00:00-05:00' '2025-12-08 00:00:00-05:00'
 '2025-12-09 00:00:00-05:00' '2025-12-10 00:00:00-05:00'
 '2025-12-11 00:00:00-05:00' '2025-12-12 00:00:00-05:00'
 '2025-12-15 00:00:00-05:00' '2025-12-16 00:00:00-05:00'
 '2025-12-17 00:00:00-05:00' '2025-12-18 00:00:00-05:00'
 '2025-12-19 00:00:00-05:00' '2025-12-22 00:00:00-05:00'
 '2025-12-23 00:00:00-05:00' '2025-12-24 00:00:00-05:00'
 '2025-12-26 00:00:00-05:00' '2025-12-29 00:00:00-05:00'
 '2025-12-30 00:00:00-05:00' '2025-12-31 00:00:00-05:00'
 '2026-01-02 00:00:00-05:00' '2026-01-05 00:00:00-05:00'
 '2026-01-06 00:00:00-05:00' '2026-01-07 00:00:00-05:00'
 '2026-01-08 00:00:00-05:00' '2026-01-09 00:00:00-05:00'
 '2026-01-12 00:00:00-05:00' '2026-01-13 00:00:00-05:00'
 '2026-01-14 00:00:00-05:00' '2026-01-15 00:00:00-05:00'
 '2026-01-16 00:00:00-05:00' '2026-01-20 00:00:00-05:00'
 '2026-01-21 00:00:00-05:00' '2026-01-22 00:00:00-05:00'
 '2026-01-23 00:00:00-05:00' '2026-01-26 00:00:00-05:00'
 '2026-01-27 00:00:00-05:00' '2026-01-28 00:00:00-05:00'
 '2026-01-29 00:00:00-05:00' '2026-01-30 00:00:00-05:00'
 '2026-02-02 00:00:00-05:00' '2026-02-03 00:00:00-05:00'
 '2026-02-04 00:00:00-05:00' '2026-02-05 00:00:00-05:00'
 '2026-02-06 00:00:00-05:00' '2026-02-09 00:00:00-05:00'
 '2026-02-10 00:00:00-05:00' '2026-02-11 00:00:00-05:00'
 '2026-02-12 00:00:00-05:00' '2026-02-13 00:00:00-05:00'
 '2026-02-17 00:00:00-05:00' '2026-02-18 00:00:00-05:00'
 '2026-02-19 00:00:00-05:00' '2026-02-20 00:00:00-05:00'
 '2026-02-23 00:00:00-05:00' '2026-02-24 00:00:00-05:00'
 '2026-02-25 00:00:00-05:00' '2026-02-26 00:00:00-05:00'
 '2026-02-27 00:00:00-05:00' '2026-03-02 00:00:00-05:00'
 '2026-03-03 00:00:00-05:00' '2026-03-04 00:00:00-05:00'
 '2026-03-05 00:00:00-05:00' '2026-03-06 00:00:00-05:00'
 '2026-03-09 00:00:00-04:00' '2026-03-10 00:00:00-04:00'
 '2026-03-11 00:00:00-04:00' '2026-03-12 00:00:00-04:00'
 '2026-03-13 00:00:00-04:00' '2026-03-16 00:00:00-04:00'
 '2026-03-17 00:00:00-04:00' '2026-03-18 00:00:00-04:00'
 '2026-03-19 00:00:00-04:00' '2026-03-20 00:00:00-04:00'
 '2026-03-23 00:00:00-04:00' '2026-03-24 00:00:00-04:00'
 '2026-03-25 00:00:00-04:00' '2026-03-26 00:00:00-04:00'
 '2026-03-27 00:00:00-04:00' '2026-03-30 00:00:00-04:00'
 '2026-03-31 00:00:00-04:00' '2026-04-01 00:00:00-04:00'
 '2026-04-02 00:00:00-04:00' '2026-04-06 00:00:00-04:00'
 '2026-04-07 00:00:00-04:00' '2026-04-08 00:00:00-04:00'
 '2026-04-09 00:00:00-04:00' '2026-04-10 00:00:00-04:00'
 '2026-04-13 00:00:00-04:00' '2026-04-14 00:00:00-04:00'
 '2026-04-15 00:00:00-04:00' '2026-04-16 00:00:00-04:00'
 '2026-04-17 00:00:00-04:00' '2026-04-20 00:00:00-04:00'
 '2026-04-21 00:00:00-04:00' '2026-04-22 00:00:00-04:00'
 '2026-04-23 00:00:00-04:00' '2026-04-24 00:00:00-04:00'
 '2026-04-27 00:00:00-04:00' '2026-04-28 00:00:00-04:00'
 '2026-04-29 00:00:00-04:00' '2026-04-30 00:00:00-04:00'
 '2026-05-01 00:00:00-04:00' '2026-05-04 00:00:00-04:00'
 '2026-05-05 00:00:00-04:00' '2026-05-06 00:00:00-04:00'
 '2026-05-07 00:00:00-04:00' '2026-05-08 00:00:00-04:00'
 '2026-05-11 00:00:00-04:00' '2026-05-12 00:00:00-04:00'
 '2026-05-13 00:00:00-04:00' '2026-05-14 00:00:00-04:00'
 '2026-05-15 00:00:00-04:00' '2026-05-18 00:00:00-04:00'
 '2026-05-19 00:00:00-04:00' '2026-05-20 00:00:00-04:00'
 '2026-05-21 00:00:00-04:00' '2026-05-22 00:00:00-04:00'
 '2026-05-26 00:00:00-04:00' '2026-05-27 00:00:00-04:00'
 '2026-05-28 00:00:00-04:00' '2026-05-29 00:00:00-04:00'
 '2026-06-01 00:00:00-04:00' '2026-06-02 00:00:00-04:00'
 '2026-06-03 00:00:00-04:00' '2026-06-04 00:00:00-04:00'
 '2026-06-05 00:00:00-04:00']
Ticker ['AAPL' 'TSLA' 'MSFT' 'GOOGL' 'AMZN' 'META' 'NVDA' 'NFLX' 'INTC' 'AMD'
 'TSM' 'BABA']
Currency ['USD']

In [23]:
df['Close'].unique()

array([203.11419678, 200.65396118, 201.86915588, ..., 127.20999908,
       125.94999695, 121.05999756], shape=(2961,))

In [24]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3012 entries, 0 to 3011
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3012 non-null   object
 1   Open          3012 non-null   float64
 2   High          3012 non-null   float64
 3   Low           3012 non-null   float64
 4   Close         3012 non-null   float64
 5   Volume        3012 non-null   int64
 6   Dividends     3012 non-null   float64
 7   Stock Splits  3012 non-null   float64
 8   Ticker        3012 non-null   object
 9   Currency      3012 non-null   object
dtypes: float64(6), int64(1), object(3)
memory usage: 235.4+ KB

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,3012.000000,3012.000000,3012.000000,3012.000000,3.012000e+03,3012.000000,3012.00000
mean,275.457624,279.034062,271.686249,275.440983,5.423722e+07,0.004393,0.00332
std,170.807281,172.570176,168.673761,170.603516,5.289156e+07,0.062143,0.18221
min,19.500000,19.549999,18.969999,19.309999,2.753900e+06,0.000000,0.00000
25%,160.102497,162.367500,157.659996,160.327503,1.911748e+07,0.000000,0.00000
50%,232.925003,235.495767,230.159377,232.782745,3.730995e+07,0.000000,0.00000
75%,370.267509,374.007622,365.212583,370.525002,6.462768e+07,0.000000,0.00000
max,789.296390,794.384398,778.990557,788.148987,5.239080e+08,2.000000,10.00000